name: Automated Test
on: [push]

jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Produce Test 1 Output
        run: python find_lowest_number.py input1.txt actual1.txt

      - name: Test 1
        run: diff expected1.txt actual1.txt

      - name: Produce Test 2 Output
        run: python find_lowest_number.py input2.txt actual2.txt

      - name: Test 2
        run: diff expected2.txt actual2.txt
